services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - type: volume
        source: wordpress-data
        target: /var/www/html
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped # on-failure restart only if it crash with a exit code != 0
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - 443:443
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "-qO-",
          "--no-check-certificate",
          "https://localhost:443",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped # on-failure restart only if it crash with a exit code != 0
    mem_limit: 10m # low limit to test OOM crash, test using:  docker exec -it nginx ash; kill 1"
volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      device: ~/data/wordpress
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ~/data/mysql
