
listen=YES
listen_ipv6=NO

# auth
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022

#chroot
chroot_local_user=YES
#secure_chroot_dir=/var/empty
allow_writeable_chroot=YES
local_root=/var/www/html

user_sub_token=$USER

# network
#connect_from_port_20=YES
#dirmessage_enable=YES
#pam_service_name=vsftpd
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
pasv_address=127.0.0.1
seccomp_sandbox=NO

# logs
log_ftp_protocol=YES
xferlog_enable=YES
xferlog_std_format=NO
dual_log_enable=YES
xferlog_file=/var/log/vsftpd/xferlog.log
vsftpd_log_file=/var/log/vsftpd/vsftpd.log

# one_process_model=YES
background=NO
