FROM alpine:latest
# FROM alpine:3.22.3

# COPY ./tools/init.sh /usr/local/bin/init.sh
# RUN chmod +x /usr/local/bin/init.sh

# RUN apk add --no-cache nginx

# # open ssl pour tls ssl ?

# EXPOSE 443

# ENTRYPOINT [ "/usr/local/bin/init.sh" ]
